### ISSUE TITLE
Sacred flame sprite and secret merchants can sometimes not spawn

### ISSUE THREAD

**Issue by burbruee** [BloodSweatAndCode/cv2r#48]
Not sure what causes it. Doesn't appear to be scanline limit as there was not much on the screen in both clips below.
https://clips.twitch.tv/PatientVastDolphinPunchTrees

https://clips.twitch.tv/ProductiveOilyPeafowlShadyLulu

Also one time one of the two moving platforms going in to rover did not spawn for me. Don't have a clip of it.

**Comment by tonylukasavage** [comment]
@burbruee any chance you have the seed for either of those highlights?

**Comment by burbruee** [comment]
Yeah I have the seed for one of them (sacred flame spot)
rYg4rZ4EJYznFBCh
it happened in a race between two players but only happened to one of them so not sure how easily it would be to reproduce.

**Comment by BloodSweatAndCode** [comment]
I was just able to reproduce the sacred flame version of this... in vanilla cv2! There's a couple things at play, but the biggest issue essentially is the fact that the moment you cross the top floor drop, the flame despawns. Additionally, if you manage to encounter enough sprites, it will also despawn. Sacred flame is so rarely encountered in vanilla, and the enemy sets are so consistent, so the condition rarely arises.

**Comment by BloodSweatAndCode** [comment]
OK, so I can't definitively prevent this from ever happening as it is possible in vanilla, or at least not without figuring out how to establish sprite priority in the core object code, which is WAY beyond the scope of this issue. I'm instead going to just ensure that no projectile enemies (fireballs, webs, or bones) spawn in the sacred flame screen, as well as both screens that have a secret merchant. This should drastically reduce the possibility of re-occurrence of this issue by keeping the sprite count down. 

Additionally, it should be noted that about 2 pixels to the right of the floor drop on the sacred flame screen is when the object for sacred flame despawns. Theoretically if you despawn the flame, then floor drop and get a lot of sprites on the screen before being able to go left towards the flame to respawn it, it may not be able to spawn due to the sprite limit. I would say for safety to **avoid using the sacred flame floor drop**.
